### ISSUE TITLE
Parser file and lexer header not completed

### ISSUE THREAD

**Issue by Asem-Abdelhady** [IVIosab/carbonic-c#20]
I have added a template for the parser file and lexer.h that we should follow to be able to implement the parser. I also added comments in the files and a todo file. Everything should be visible in the parser branch. Please pull the branch to your local machine and see the changes. Warning! Make sure you pull the origin main to the local main so we don't have problems when we try to merge the parser branch to the main in the future.

**Comment by PATH242** [comment]
Acknowledged.

**Comment by Asem-Abdelhady** [comment]
This issue will be closed only when we finialize the parser.ypp, lexer.l and lexer.h files. the files are unstable for now and prone to change with little modifications, for instance while doing the AST.
