### ISSUE TITLE
CMake Support and project structure

### ISSUE THREAD

**Issue by IVIosab** [IVIosab/carbonic-c#22]
Make a CMake file and reorganize the repo (e.g. https://medium.com/swlh/c-project-structure-for-cmake-67d60135f6f5)

**Comment by Asem-Abdelhady** [comment]
I believe it is not necessary to make a CMake, at least for now. If we have time later we can make it!

**Comment by IVIosab** [comment]
Yea, Just leaving it as an issue to not forget about it
